# Generated by Django 2.1.5 on 2019-02-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190204_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_games',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_wins',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
