# Generated by Django 2.1.5 on 2019-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('player_level', models.SmallIntegerField(default=0, null=True)),
                ('total_games', models.SmallIntegerField(default=0, null=True)),
                ('total_wins', models.SmallIntegerField(default=0, null=True)),
                ('inQueue', models.BooleanField(default=False)),
                ('inMatch', models.BooleanField(default=False)),
            ],
        ),
    ]
