# Generated by Django 2.1.5 on 2019-04-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
