# Generated by Django 2.1.5 on 2019-04-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20190417_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('created', models.DateTimeField(editable=False)),
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('court', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='player_level',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_games',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_wins',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='players',
            field=models.ManyToManyField(limit_choices_to={'inQueue': False}, to='queues.Player'),
        ),
    ]
