# Generated by Django 2.1.5 on 2019-04-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_auto_20190420_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='onGoing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='players',
            field=models.ManyToManyField(limit_choices_to={'inQueue': False}, related_name='queues', to='queues.Player'),
        ),
    ]
