# Generated by Django 2.1.5 on 2019-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_auto_20190421_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='players',
            field=models.ManyToManyField(related_name='queues', to='queues.Player'),
        ),
    ]
