# Generated by Django 2.1.5 on 2019-02-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_auto_20190208_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Court',
        ),
        migrations.DeleteModel(
            name='QueueRecord',
        ),
    ]
