# Generated by Django 2.1.5 on 2019-02-21 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0005_auto_20190218_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.AutoField(primary_key=True, serialize=False)),
                ('court_name', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'court',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.TextField()),
            ],
            options={
                'db_table': 'match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('mt_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'match_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('player_level', models.SmallIntegerField(blank=True, null=True)),
                ('total_games', models.SmallIntegerField(default=0, null=True)),
                ('total_win', models.SmallIntegerField(default=0, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'venue',
                'managed': False,
            },
        ),
    ]
