# Generated by Django 2.1.5 on 2019-04-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_auto_20190421_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('startDT', models.DateTimeField()),
                ('endDT', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('winner_id', models.AutoField(primary_key=True, serialize=False)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='queues.Match')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='match_type',
            field=models.CharField(choices=[('S', 'Singles'), ('D', 'Doubles')], default='S', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AddField(
            model_name='winner',
            name='player',
            field=models.ManyToManyField(to='queues.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='queues.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='queuedAt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.Queue'),
        ),
    ]
