# Generated by Django 2.1.5 on 2019-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_court_match_matchtype_player_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.SmallIntegerField(blank=True, null=True)),
                ('type', models.SmallIntegerField(blank=True, null=True)),
                ('team1_p1', models.SmallIntegerField(blank=True, null=True)),
                ('team1_p2', models.SmallIntegerField(blank=True, null=True)),
                ('team2_p1', models.SmallIntegerField(blank=True, null=True)),
                ('team2_p2', models.SmallIntegerField(blank=True, null=True)),
                ('court_id', models.SmallIntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'queue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.SmallIntegerField(blank=True, null=True)),
                ('type', models.SmallIntegerField(blank=True, null=True)),
                ('team1_p1', models.SmallIntegerField(blank=True, null=True)),
                ('team1_p2', models.SmallIntegerField(blank=True, null=True)),
                ('team2_p1', models.SmallIntegerField(blank=True, null=True)),
                ('team2_p2', models.SmallIntegerField(blank=True, null=True)),
                ('court_id', models.SmallIntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
    ]
