# Generated by Django 2.1.5 on 2019-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_auto_20190424_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='match_type',
            field=models.CharField(choices=[('S', 'Singles'), ('D', 'Doubles')], default='S', max_length=1),
        ),
    ]
