# Generated by Django 2.1.5 on 2019-04-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_player_match_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='match_type',
        ),
    ]
