# Generated by Django 2.1.5 on 2019-04-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0009_auto_20190424_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('startDT', models.DateTimeField(blank=True, default=None, null=True)),
                ('onGoing', models.BooleanField(default=False)),
                ('endDT', models.DateTimeField(blank=True, default=None, null=True)),
                ('players', models.ManyToManyField(to='queues.Player')),
                ('queuedAt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.Queue')),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('winner_id', models.AutoField(primary_key=True, serialize=False)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='queues.Match')),
                ('player', models.ManyToManyField(to='queues.Player')),
            ],
        ),
    ]
