# Generated by Django 2.1.5 on 2019-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0010_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='court_num',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
