# Generated by Django 2.1.5 on 2019-04-27 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0011_match_court_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='umpire',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Umpire'),
        ),
        migrations.AlterField(
            model_name='match',
            name='court_num',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Court ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='endDT',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='onGoing',
            field=models.BooleanField(default=True, verbose_name='Match in Progress'),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='queues.Player', verbose_name='Players in Match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='queuedAt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.Queue', verbose_name='Queued at'),
        ),
        migrations.AlterField(
            model_name='match',
            name='startDT',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=64, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='inMatch',
            field=models.BooleanField(default=False, verbose_name='Currently in Match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='inQueue',
            field=models.BooleanField(default=False, verbose_name='Currently in Queue'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_level',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_games',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Game Count'),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_wins',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Total Wins'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='court',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of Courts'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='match_type',
            field=models.CharField(choices=[('S', 'Singles'), ('D', 'Doubles')], default='S', max_length=1, verbose_name='Match Type'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='onGoing',
            field=models.BooleanField(default=True, verbose_name='Queue in Progress'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='players',
            field=models.ManyToManyField(related_name='queues', to='queues.Player', verbose_name='Players in Queue'),
        ),
    ]
