# Generated by Django 2.1.5 on 2019-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0014_auto_20190427_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='endDT',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='startDT',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
