# Generated by Django 2.1.5 on 2019-04-27 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0016_auto_20190427_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='endDT',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='startDT',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Start Time'),
        ),
    ]
