# Generated by Django 2.1.5 on 2019-04-29 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0021_auto_20190429_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='court_num',
            field=models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Court ID'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='court',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Courts'),
        ),
    ]
