# Generated by Django 2.1.5 on 2019-02-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'venue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.SmallIntegerField()),
                ('court_name', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='courts.Venue')),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'court',
                'managed': False,
            },
        ),
    ]
