# Generated by Django 2.1.5 on 2019-02-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20190207_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuerecord',
            name='queue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
