# Generated by Django 2.1.5 on 2019-02-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuerecord',
            name='queue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
