# Generated by Django 2.1.5 on 2019-02-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20190207_0122'),
        ('queues', '0003_auto_20190207_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueCourt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFree', models.BooleanField(default=True)),
                ('queue_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.QueueRecord')),
            ],
        ),
        migrations.CreateModel(
            name='QueuePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0)),
                ('games_won', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ManyToManyField(to='players.Player')),
                ('queue_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.QueueRecord')),
            ],
        ),
    ]
