# Generated by Django 2.1.5 on 2019-02-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20190207_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
    ]
