# Generated by Django 2.1.5 on 2019-02-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20190221_1650'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
    ]
